version: '3.9'

services:

  db: 
    restart: always
    image: postgres:14.4-alpine3.16
    ports:
      - 5432:5432
    volumes:
      - db-cs:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=onxyhdfdpxbtxg
      - POSTGRES_PASSWORD=f241d679f8103ebaa316c48e471cd3d90fefafe6d2306bb188ea1166fbb62c2c
      - POSTGRES_DB=d30esmmejcpa7d




  api: 
    restart: always
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/app_rest
    depends_on:
      - db


volumes:
  db-cs:
